name: string_scanner
version: 1.1.0-nullsafety.4-dev

description: A class for parsing strings using a sequence of patterns.
homepage: https://github.com/dart-lang/string_scanner

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  charcode: '>=1.2.0-nullsafety <1.2.0'
  source_span: '>=1.8.0-nullsafety <1.8.0'

dev_dependencies:
  test: '>=1.16.0-nullsafety <1.16.0'
